name: configura_tiles
description: Configura Tiles is a Flutter package designed for creating screens with a list tile setup, such as settings screens.
version: 0.0.2
homepage: https://github.com/TheSageAnomaly/configura_tiles.git
repository: https://github.com/TheSageAnomaly/configura_tiles.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  blurrycontainer: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

 assets:
   - assets/images/
